### ISSUE TITLE
Genes relationships

### ISSUE THREAD

**Issue by mxfly14** [recursionpharma/maes_microscopy#5]
Hello,

Thanks for your work. Can you provide the gene relationships dataset you used to asses the performance of the model ? 

By the way why were you looking at the bottom 5% of cosine distance ?

By advance, thanks

**Comment by kian-kd** [comment]
Hi there, thank you!

Yes, you can find those datasets here in [this other Recursion Repo](https://github.com/recursionpharma/EFAAR_benchmarking/tree/trunk) which may also be of use as you work on benchmarking: https://github.com/recursionpharma/EFAAR_benchmarking/tree/trunk/efaar_benchmarking/benchmark_annotations

We look at the bottom 5% of cosine distance because we have observed that sometimes high-oppositeness between the foundation model embeddings can capture informative biological signal as high-similarity between embeddings does.

**Comment by mxfly14** [comment]
Hello,

Thank you for your reply. I am gonna check those repo. Do you have any
biological explanation for this high-oppositeness information?

Best regards,

Maxime Sanchez

**Comment by kian-kd** [comment]
As Safiye Celik describes, consider the example of MTOR-TSC2:
TSC2, along with TSC1, forms a complex that inhibits the activity of MTOR. Two opposite states of MTOR (inhibited state as represented by the MTOR KO embedding, and active state as represented by the TSC2 KO embedding) can be captured by the opposite directions of the embeddings for these two genes.
